defmodule Pepe.Usage.Invoice do
  @moduledoc """
  Render a billing invoice (from `Pepe.Usage.invoice/2`) as CSV for spreadsheets
  or Markdown for a human — an email body, a Telegram message, a PDF source.
  """

  @doc "A stable filename stem for an invoice, e.g. `acme-2026-07`."
  def basename(%{company: company, period: %{label: label}}),
    do: "#{safe(company)}-#{label}"

  @doc "Render the invoice as CSV: one row per model plus a TOTAL row."
  def to_csv(inv) do
    header = ["model", "input_tokens", "output_tokens", "total_tokens", "cost", "billable"]

    rows =
      Enum.map(inv.line_items, fn li ->
        [li.key, li.in, li.out, li.total, money2(li.cost), money2(li.billable)]
      end)

    total = [
      "TOTAL",
      inv.totals.in,
      inv.totals.out,
      inv.totals.total,
      money2(inv.totals.cost),
      money2(inv.totals.billable)
    ]

    ([header | rows] ++ [total])
    |> Enum.map_join("\n", fn cells -> Enum.map_join(cells, ",", &csv_cell/1) end)
  end

  @doc "Render the invoice as Markdown — a readable statement for a client."
  def to_markdown(inv) do
    cur = inv.currency
    gen = inv.generated_at |> DateTime.from_unix!() |> Calendar.strftime("%Y-%m-%d %H:%M UTC")

    lines =
      Enum.map(inv.line_items, fn li ->
        "| #{li.key} | #{li.total} | #{money(li.cost, cur)} | #{money(li.billable, cur)} |"
      end)

    markup_note =
      if inv.markup != 1.0 do
        "\nProvider cost **#{money(inv.totals.cost, cur)}** × markup **#{inv.markup}** = amount due **#{money(inv.totals.billable, cur)}**.\n"
      else
        "\nAmount due **#{money(inv.totals.billable, cur)}** (billed at provider cost, no markup).\n"
      end

    """
    # Invoice — #{inv.company}

    **Period:** #{inv.period.label}
    **Currency:** #{cur}
    **Generated:** #{gen}

    | Model | Tokens | Cost | Billable |
    |---|---:|---:|---:|
    #{Enum.join(lines, "\n")}
    | **Total** | **#{inv.totals.total}** | **#{money(inv.totals.cost, cur)}** | **#{money(inv.totals.billable, cur)}** |
    #{markup_note}
    *#{inv.totals.count} model calls metered. Generated by Pepe.*
    """
  end

  defp money(amount, currency), do: "#{currency} #{money2(amount)}"
  defp money2(amount), do: :erlang.float_to_binary(amount / 1, decimals: 2)

  defp csv_cell(v) do
    s = to_string(v)

    if String.contains?(s, [",", "\"", "\n"]),
      do: "\"#{String.replace(s, "\"", "\"\"")}\"",
      else: s
  end

  defp safe(name), do: String.replace(to_string(name), ~r/[^A-Za-z0-9_-]+/, "_")
end
