defmodule PepeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pepe

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pepe_key",
    signing_salt: "EUco6d8a",
    same_site: "Lax"
  ]

  # :uri lets the dashboard read back the host it's being accessed at (e.g. to
  # fill in a widget embed snippet with the real address, not a placeholder).
  #
  # check_origin is custom (not Phoenix's default of "same host as this server") so
  # this socket allows exactly what PepeWeb.NetworkGuard already allowed through at
  # the HTTP layer for the page itself - a loopback host, a `dashboard.allowed_hosts`
  # entry, or (once a password is set) anything, which is what makes the dashboard's
  # interactive features actually work behind a reverse proxy, a custom domain, or a
  # `--tunnel` session (a fresh, unconfigurable *.trycloudflare.com host every time).
  # Without this, the page loads but every LiveView feature on it silently breaks.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:uri, session: @session_options], check_origin: {__MODULE__, :check_live_origin?, []}],
    longpoll: [connect_info: [:uri, session: @session_options], check_origin: {__MODULE__, :check_live_origin?, []}]

  # Streaming agent conversations over WebSocket. `peer_data` gives the socket the
  # caller's address so it can allow loopback and refuse remote when no tokens exist.
  # `check_origin` is custom (not the Phoenix default of "same host as this server")
  # so a registered widget token's own site can also open a cross-origin connection -
  # see PepeWeb.AgentSocket.check_origin?/1 for what it actually allows.
  socket "/socket", PepeWeb.AgentSocket,
    websocket: [connect_info: [:peer_data], check_origin: {PepeWeb.AgentSocket, :check_origin?, []}],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pepe,
    gzip: not code_reloading?,
    only: PepeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {PepeWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PepeWeb.Router

  # Phoenix's socket :connect_info only exposes a fixed key set (:uri is this
  # server's OWN address, not the browser's cross-origin header; :x_headers only
  # covers "x-"-prefixed headers), and the WebSocket upgrade's check_origin callback
  # runs before the query string (and thus the token) is available - see
  # PepeWeb.AgentSocket's moduledoc. So a widget token's own allowed_origin can't be
  # verified against the real Origin header at either of those points. This plug
  # pipeline is what the "/socket" upgrade itself runs through (see
  # do_socket_dispatch/2 in Phoenix.Endpoint - it's a synchronous plug.call in the
  # same process, not a spawn), so stash the raw header here; AgentSocket.connect/3
  # reads it back via the process dictionary to enforce it per-token.
  def call(conn, opts) do
    Process.put(:pepe_ws_request_origin, conn |> Plug.Conn.get_req_header("origin") |> List.first())
    # Same reason as the origin above: the socket's own `:connect_info` can't give the real client
    # IP behind a trusted proxy, and the widget rate-limit must key on something the caller can't
    # rotate for free (unlike the client-supplied session id). Stash the resolved client IP here,
    # where the full conn (and the trusted-proxy chain) is available.
    Process.put(:pepe_ws_client_ip, PepeWeb.RemoteClient.ip(conn))
    super(conn, opts)
  end

  @doc false
  @spec check_live_origin?(URI.t()) :: boolean()
  def check_live_origin?(%URI{host: nil}), do: false
  def check_live_origin?(%URI{host: host}), do: PepeWeb.NetworkGuard.host_allowed?(host)
end
