defmodule PepeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pepe

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pepe_key",
    signing_salt: "EUco6d8a",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Streaming agent conversations over WebSocket. `peer_data` gives the socket the
  # caller's address so it can allow loopback and refuse remote when no tokens exist.
  # `check_origin` is custom (not the Phoenix default of "same host as this server")
  # so a registered widget token's own site can also open a cross-origin connection -
  # see PepeWeb.AgentSocket.check_origin?/1 for what it actually allows.
  socket "/socket", PepeWeb.AgentSocket,
    websocket: [connect_info: [:peer_data], check_origin: {PepeWeb.AgentSocket, :check_origin?, []}],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pepe,
    gzip: not code_reloading?,
    only: PepeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {PepeWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PepeWeb.Router
end
