import Config

# The database itself (:database, the actual file path) is resolved at start_link
# time from PEPE_HOME - see Pepe.Repo.init/2 - not set here. SQLite is single-writer
# regardless of pool size, so a pool of 1 lets Ecto's own connection queue serialize
# writes instead of fighting SQLITE_BUSY retries; wal mode is also what makes a hot
# file-copy backup (`mix pepe backup`) safe to take while the app is running.
config :pepe, Pepe.Repo,
  pool_size: 1,
  journal_mode: :wal,
  busy_timeout: 5_000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pepe, PepeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "O8xcWkxqZZGS3iq4Bn0p9rGQ/c+Vw8FweHJrBJkXIGwjkkBQwiDRz0AMN4s8i4/J",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pepe, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pepe, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :pepe, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
