defmodule Pepe.Commitments.Migration do
  @moduledoc """
  One-time, operator-run import of commitments from their old home (`config.json`'s
  `"commitments"` section) into `Pepe.Repo` - see `Pepe.Config.Commitment`'s moduledoc for
  why they moved. Deliberately not automatic: `Pepe.Config.load/1` already runs a generic,
  silent migration step on every disk read, but copying that pattern here would be unsafe -
  `load/0` is the single most-called function in the codebase, including by every test that
  never starts `Pepe.Repo`, so a side-effecting import there would crash any of them whose
  fixture config still carries the key. Run once, deliberately, after upgrading and before
  restarting the long-lived process: `mix pepe config migrate-commitments`.

  Idempotent and crash-safe: re-running is always safe. Every row is inserted with
  `on_conflict: :nothing`, so an already-migrated id is silently skipped rather than
  re-inserted or erroring. The `"commitments"` key in `config.json` is deleted only after
  every entry has been inserted (or was already present) successfully - a crash before that
  point is always safe to retry from scratch, and a malformed individual entry is reported
  without deleting the key, so nothing is silently dropped.
  """

  alias Pepe.Config
  alias Pepe.Config.Commitment
  alias Pepe.Repo

  @type report :: %{imported: non_neg_integer(), already_present: non_neg_integer(), failed: [{String.t(), term()}]}

  @doc """
  Import every entry still in config.json's `"commitments"` section. Deletes that key once
  every entry succeeds (inserted or already present); leaves it in place, and reports which
  ids failed and why, if anything didn't.
  """
  @spec run() :: report()
  def run do
    raw = Config.load() |> Map.get("commitments", %{})

    {oks, fails} =
      raw
      |> Enum.map(fn {id, entry} -> {id, import_entry(id, entry)} end)
      |> Enum.split_with(fn {_id, result} -> match?({:ok, _}, result) end)

    report = %{
      imported:
        Enum.count(oks, fn
          {_id, {:ok, :inserted}} -> true
          _ -> false
        end),
      already_present:
        Enum.count(oks, fn
          {_id, {:ok, :already_present}} -> true
          _ -> false
        end),
      failed: Enum.map(fails, fn {id, {:error, reason}} -> {id, reason} end)
    }

    if report.failed == [] and map_size(raw) > 0 do
      Config.update(&Map.delete(&1, "commitments"))
    end

    report
  end

  # A legacy entry's value should always be a map (that's the only shape anything ever
  # wrote), but this reads a file an operator could have hand-edited - fail this one entry
  # into `report.failed`, not a crash that takes the whole import down with it.
  defp import_entry(_id, entry) when not is_map(entry), do: {:error, {:not_a_map, entry}}
  defp import_entry(id, entry), do: import_one(Map.put(entry, "id", id))

  defp import_one(map) do
    changeset = Commitment.from_map(map)

    if changeset.valid? do
      # Repo.insert/2's on_conflict: :nothing gives no reliable signal here (id isn't
      # autogenerated, so a skipped conflict doesn't come back nil the way Ecto's docs
      # describe for an autogenerated key - verified empirically, not assumed) - insert_all's
      # returned row count is the one accurate way to tell "inserted" from "already there".
      row = changeset |> Ecto.Changeset.apply_changes() |> Map.from_struct() |> Map.drop([:__meta__])

      # No :conflict_target: a re-imported row conflicts on `id` when it is a genuine
      # resume, but could in principle also collide with the active-commitment unique
      # index (agent + normalized_text) - `ON CONFLICT (id) DO NOTHING` only silences
      # the column it names, so a row that would violate the OTHER index too still
      # raises unhandled. A bare on_conflict: :nothing skips on any violation, which is
      # exactly "this already exists in some form, move on" - the right call for an
      # idempotent import, not just an id-keyed retry.
      case Repo.insert_all(Commitment, [row], on_conflict: :nothing) do
        {1, _} -> {:ok, :inserted}
        {0, _} -> {:ok, :already_present}
      end
    else
      {:error, changeset.errors}
    end
  end
end
