defmodule Pepe.Watches.Migration do
  @moduledoc """
  One-time, operator-run import of watches from their old home (`config.json`'s
  `"watches"` section) into `Pepe.Repo` - see `Pepe.Config.Watch`'s moduledoc for why
  they moved. Not run automatically - see `Pepe.Commitments.Migration`'s moduledoc for
  why (the same reasoning applies verbatim). Run once, deliberately, after upgrading and
  before restarting the long-lived process, via `mix pepe config migrate-data`.

  Idempotent and crash-safe, the same shape as `Pepe.Commitments.Migration.run/0`: every
  row is inserted with `on_conflict: :nothing`, so an already-migrated id is silently
  skipped rather than re-inserted or erroring. The `"watches"` key in `config.json` is
  deleted only after every entry has been inserted (or was already present)
  successfully - a crash before that point is always safe to retry from scratch, and a
  malformed individual entry is reported without deleting the key, so nothing is
  silently dropped.
  """

  alias Pepe.Config
  alias Pepe.Config.Watch
  alias Pepe.Repo

  @type report :: %{imported: non_neg_integer(), already_present: non_neg_integer(), failed: [{String.t(), term()}]}

  @doc """
  Import every entry still in config.json's `"watches"` section. Deletes that key once
  every entry succeeds (inserted or already present); leaves it in place, and reports
  which ids failed and why, if anything didn't.
  """
  @spec run() :: report()
  def run do
    raw = Config.load() |> Map.get("watches", %{})

    {oks, fails} =
      raw
      |> Enum.map(fn {id, entry} -> {id, import_entry(id, entry)} end)
      |> Enum.split_with(fn {_id, result} -> match?({:ok, _}, result) end)

    report = %{
      imported:
        Enum.count(oks, fn
          {_id, {:ok, :inserted}} -> true
          _ -> false
        end),
      already_present:
        Enum.count(oks, fn
          {_id, {:ok, :already_present}} -> true
          _ -> false
        end),
      failed: Enum.map(fails, fn {id, {:error, reason}} -> {id, reason} end)
    }

    if report.failed == [] and map_size(raw) > 0 do
      Config.update(&Map.delete(&1, "watches"))
    end

    report
  end

  # A legacy entry's value should always be a map (that's the only shape anything ever
  # wrote), but this reads a file an operator could have hand-edited - fail this one entry
  # into `report.failed`, not a crash that takes the whole import down with it.
  defp import_entry(_id, entry) when not is_map(entry), do: {:error, {:not_a_map, entry}}
  defp import_entry(id, entry), do: import_one(Map.put(entry, "id", id))

  defp import_one(map) do
    changeset = Watch.from_map(map)

    if changeset.valid? do
      row = changeset |> Ecto.Changeset.apply_changes() |> Map.from_struct() |> Map.drop([:__meta__])

      # Repo.insert/2's on_conflict: :nothing gives no reliable signal here (id isn't
      # autogenerated) - insert_all's returned row count is the accurate way to tell
      # "inserted" from "already there", same as Pepe.Commitments.Migration.
      case Repo.insert_all(Watch, [row], on_conflict: :nothing) do
        {1, _} -> {:ok, :inserted}
        {0, _} -> {:ok, :already_present}
      end
    else
      {:error, changeset.errors}
    end
  end
end
